modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
description = "A NeoForge mod."

# --- Required Dependencies ---

# NeoForge
[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.219, 21.1.299)"
ordering = "NONE"
side = "BOTH"

# Minecraft
[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

# --- Mod Dependencies from build.gradle ---

# Create
[[dependencies.${mod_id}]]
modId = "create"
type = "required"
versionRange = "[6.0.10, 6.1.0)"
ordering = "NONE"
side = "BOTH"

# FootLib (My API)
[[dependencies.${mod_id}]]
modId = "footlib"
type = "required"
versionRange = "[0.0.1.1, 1.0.0.0)"
ordering = "NONE"
side = "BOTH"
reason="This allows for every Util to work and the entire API."

# JEI(Just Enough Items)
[[dependencies.${mod_id}]]
modId="jei"
type="optional"
versionRange="[19.27.0,)"
ordering="NONE"
side="BOTH"
